### ISSUE TITLE
Two (related) timestamp issues

### ISSUE THREAD

**Issue by RobThree** [jefffhaynes/PcapNet#1]
First issue:

https://github.com/jefffhaynes/PcapNet/blob/2990770289021f6891fd35748a50dc72f6d82551/PcapNet/Packet.cs#L8

Actually, the [timestamp is specified to be GMT](https://wiki.wireshark.org/Development/LibpcapFileFormat), so you could use `DateTimeKind.Utc` instead of `DateTimeKind.Unspecified`

---
Second: 

https://github.com/jefffhaynes/PcapNet/blob/2990770289021f6891fd35748a50dc72f6d82551/PcapNet/Packet.cs#L27-L28

You're using millisecond resolution here (and thus dropping microseconds). A timestamp that is, for example, `15:14:38.487919` is (de)serialized as `15:14:38.488000`. Proposed fix:

```c#
public DateTime Timestamp => Epoch + TimeSpan.FromSeconds(TimestampSeconds) +
                                     TimeSpan.FromTicks(TimestampMicroseconds * 10);
```

**Comment by jefffhaynes** [comment]
Thanks for the comments!  The millisecond method takes a double so I don’t know that precision is lost. Is there something in the documentation or elsewhere that makes you think it is?  It’s definitely possible but I assumed it handled that correctly.

—
Planning for failure is even dumber than regular planning
________________________________

**Comment by RobThree** [comment]
>  It’s definitely possible but I assumed it handled that correctly.

I would've assumed this too and was actually surprised it didn't...

Try this:
```c#
var d = new DateTime(2017, 12, 13, 0, 0, 0);
Console.WriteLine((d + TimeSpan.FromMilliseconds(123.456)).ToString("o"));
Console.WriteLine((d + TimeSpan.FromTicks(123456 * 10)).ToString("o"));
```
Output:
```
2017-12-13T00:00:00.1230000
2017-12-13T00:00:00.1234560
```

See [Adding fractional milliseconds (microseconds) to a DateTime or TimeSpan not working](https://github.com/dotnet/corefx/issues/24501) and [DateTime.AddMilliseconds](https://msdn.microsoft.com/en-us/library/system.datetime.addmilliseconds):

> Note that this value is rounded to the nearest integer.

**Comment by jefffhaynes** [comment]
What!  Ok, I’ll fix it, thanks!

—
Planning for failure is even dumber than regular planning
________________________________
